#!/usr/bin/env python3
# core/tts.py — Clean Shot: platform-agnostic TTS dispatcher
# Routes to platform-specific implementation:
#   Linux:   platforms/linux/tts_linux.py   (pyttsx3, fully offline)
#   Windows: platforms/windows/tts_windows.py (Windows SAPI, built-in)
#   iOS:     platforms/ios/tts_ios.py        (AVSpeechSynthesizer bridge)
#
# CB radio style voice strings are generated by claude/prompts.py
# Example: "Smokey's reporting black ice ahead good buddy — back it down"
#
# Battery budget: TTS fires on alerts only, not on every data refresh.
# TODO: implement platform detection + dispatch in module sprint

import sys
import platform


def speak(text: str, config: dict) -> bool:
    """
    Speak text using the platform TTS engine.
    Returns True if speech was dispatched, False if TTS is disabled/unavailable.
    """
    if not config.get("tts_enabled", False):
        return False

    plat = platform.system().lower()

    try:
        if plat == "linux":
            from platforms.linux.tts_linux import speak_linux
            return speak_linux(text)
        elif plat == "windows":
            from platforms.windows.tts_windows import speak_windows
            return speak_windows(text)
        elif plat == "darwin":
            # macOS — use say command as fallback until iOS bridge ready
            import subprocess
            subprocess.Popen(["say", text])
            return True
    except Exception as e:
        print(f"⚠  TTS error: {e}", file=sys.stderr)

    return False


def speak_alert(alert_type: str, config: dict) -> bool:
    """
    Speak a pre-built CB-style alert string for a known alert type.
    Delegates to claude/prompts.py for the voice string.
    """
    from claude.prompts import cb_voice_alert
    text = cb_voice_alert(alert_type)
    if text:
        return speak(text, config)
    return False
