name: Build Debian Package

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install build tools
      run: |
        sudo apt update
        sudo apt install -y build-essential debhelper dpkg-dev

    - name: Build package
      run: dpkg-buildpackage -us -uc -b

    - name: Move package
      run mv ../*.deb .

    - name: Upload .deb
      uses: actions/upload-artifact@v4
      with:
        name: weather-cli-deb
        path: "*.deb"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: weather-cli-deb
        path: ../*.deb

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: ../*.deb
