name: Build Weather CLI

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Debian package
        run: |
          sudo apt update
          sudo apt install -y build-essential debhelper dpkg-dev
          dpkg-buildpackage -us -uc -b
          mv ../*.deb .

      - name: Prepare cross-platform builds
        run: |
          cp weather weather-linux
          cp weather weather-macos
          cp weather weather-windows.sh

          chmod +x weather-linux
          chmod +x weather-macos

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: weather-cli
          path: |
            *.deb
            weather-linux
            weather-macos
            weather-windows.sh

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.deb
            weather-linux
            weather-macos
            weather-windows.sh
